services:
  backend:
    build:
      context: .
      dockerfile: /backend/Dockerfile
    container_name: django-backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./manage.py:/app/manage.py
      - ./api:/app/api
    env_file:
      - .env
    depends_on:
      - db
    environment:
    - DJANGO_SETTINGS_MODULE=backend.settings


  frontend:
    build:
      context: .
      dockerfile: /frontend/Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
